GET http://localhost:8000
###
POST http://192.168.0.105:8000/given-cards
Content-Type: application/json

{
  "data": [{"name": "chariot", "reversed": "true"}, {"name": "empress", "reversed": "false"}, {"name": "moon", "reversed": "true"}]
}